avm_dbt:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: AVM_ROLE
      database: AVM_DB
      warehouse: AVM_WH
      schema: STAGING
      threads: 4
      client_session_keep_alive: False
      query_tag: dbt_avm

    prod:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: AVM_ROLE
      database: AVM_DB
      warehouse: AVM_WH
      schema: MART
      threads: 8
      client_session_keep_alive: False
      query_tag: dbt_avm_prod
